import type { Movie } from '@/types/movie';

export const featuredMovie: Movie = {
  id: 1,
  title: 'Dune: Part Two',
  thaiTitle: 'ดูน ภาคสอง',
  year: '2024',
  rating: '8.5',
  genres: ['Sci-Fi', 'Adventure', 'Drama'],
  overview:
    'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
  poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
  backdrop: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
  trailerUrl: 'https://www.youtube.com/results?search_query=Dune+Part+Two+official+trailer',
};

export const movies: Movie[] = [
  featuredMovie,
  {
    id: 2,
    title: 'Inside Out 2',
    thaiTitle: 'มหัศจรรย์อารมณ์อลเวง 2',
    year: '2024',
    rating: '7.6',
    genres: ['Animation', 'Family', 'Comedy'],
    overview: 'Riley enters her teenage years as new emotions arrive and shake up headquarters.',
    poster: 'https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg',
  },
  {
    id: 3,
    title: 'Furiosa: A Mad Max Saga',
    thaiTitle: 'ฟูริโอซ่า มหากาพย์แมดแม็กซ์',
    year: '2024',
    rating: '7.5',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    overview: 'The origin story of renegade warrior Furiosa before her encounter with Mad Max.',
    poster: 'https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg',
  },
  {
    id: 4,
    title: 'Godzilla x Kong: The New Empire',
    thaiTitle: 'ก็อดซิลล่า ปะทะ คอง อาณาจักรใหม่',
    year: '2024',
    rating: '7.1',
    genres: ['Action', 'Adventure', 'Fantasy'],
    overview: 'Two ancient titans rise again as a hidden threat challenges the balance of the world.',
    poster: 'https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg',
  },
  {
    id: 5,
    title: 'Kingdom of the Planet of the Apes',
    thaiTitle: 'อาณาจักรแห่งพิภพวานร',
    year: '2024',
    rating: '7.2',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    overview: 'Many years after Caesar, a young ape begins a journey that will define the future.',
    poster: 'https://image.tmdb.org/t/p/w500/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg',
  },
  {
    id: 6,
    title: 'Civil War',
    thaiTitle: 'วิบัติสมรภูมิเมืองเดือด',
    year: '2024',
    rating: '6.9',
    genres: ['Drama', 'Action', 'War'],
    overview: 'A team of journalists travels across a fractured nation during a near-future conflict.',
    poster: 'https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg',
  },
  {
    id: 7,
    title: 'The Batman',
    thaiTitle: 'เดอะ แบทแมน',
    year: '2022',
    rating: '7.8',
    genres: ['Crime', 'Action', 'Drama'],
    overview: 'Batman ventures into Gotham City underworld when a sadistic killer leaves behind cryptic clues.',
    poster: 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
  },
  {
    id: 8,
    title: 'Oppenheimer',
    thaiTitle: 'ออพเพนไฮเมอร์',
    year: '2023',
    rating: '8.1',
    genres: ['Drama', 'History'],
    overview: 'The story of J. Robert Oppenheimer and the creation of the atomic bomb.',
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
  },
  {
    id: 9,
    title: 'Spider-Man: Across the Spider-Verse',
    thaiTitle: 'ผงาดข้ามจักรวาลแมงมุม',
    year: '2023',
    rating: '8.4',
    genres: ['Animation', 'Action', 'Adventure'],
    overview: 'Miles Morales catapults across the Multiverse and meets a team of Spider-People.',
    poster: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
  },
  {
    id: 10,
    title: 'John Wick: Chapter 4',
    thaiTitle: 'จอห์น วิค แรงกว่านรก 4',
    year: '2023',
    rating: '7.7',
    genres: ['Action', 'Crime', 'Thriller'],
    overview: 'John Wick uncovers a path to defeating The High Table, but must face a powerful new enemy.',
    poster: 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
  },
  {
    id: 11,
    title: 'Wonka',
    thaiTitle: 'วองก้า',
    year: '2023',
    rating: '7.1',
    genres: ['Fantasy', 'Family', 'Comedy'],
    overview: 'A young chocolate-maker dreams of opening a shop in a city known for its sweets.',
    poster: 'https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/yOm993lsJyPmBodlYjgpPwBjXP9.jpg',
  },
  {
    id: 12,
    title: 'A Quiet Place: Day One',
    thaiTitle: 'ดินแดนไร้เสียง วันที่หนึ่ง',
    year: '2024',
    rating: '6.8',
    genres: ['Horror', 'Sci-Fi', 'Thriller'],
    overview: 'A woman experiences the terrifying early moments of an alien invasion in New York City.',
    poster: 'https://image.tmdb.org/t/p/w500/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg',
  },
];

const byGenre = (targetGenres: string[]) =>
  movies.filter((movie) => movie.genres.some((genre) => targetGenres.includes(genre)));

export const movieRows = [
  {
    title: 'กำลังจะเข้าฉาย',
    subtitle: 'Featured and new releases in cinematic rows',
    movies,
  },
  {
    title: 'แอ็กชัน / ผจญภัย',
    subtitle: 'High-energy stories with bold visual worlds',
    movies: byGenre(['Action', 'Adventure']),
  },
  {
    title: 'ไซไฟ / แฟนตาซี',
    subtitle: 'Large-scale worlds, future stories, and fantasy adventures',
    movies: byGenre(['Sci-Fi', 'Fantasy']),
  },
  {
    title: 'ครอบครัว / แอนิเมชัน',
    subtitle: 'Accessible titles with bright visual storytelling',
    movies: byGenre(['Animation', 'Family', 'Comedy']),
  },
  {
    title: 'ดราม่า / ประวัติศาสตร์',
    subtitle: 'Character-driven stories and award-style films',
    movies: byGenre(['Drama', 'History', 'War']),
  },
  {
    title: 'ระทึกขวัญ / สยองขวัญ',
    subtitle: 'Dark, suspenseful, and atmospheric titles',
    movies: byGenre(['Thriller', 'Horror', 'Crime']),
  },
];
